# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyrow < Formula
  desc "CLI for the Anyrow extraction API"
  homepage "https://anyrow.ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_amd64.tar.gz"
      sha256 "37c4b07210d3117ad0134f4bbaef7d80e8a3bd627108c2809890e572ef85a7ef"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_arm64.tar.gz"
      sha256 "4a955bd0d305a8b8a2e844deef6f62fd3a62835c00bb88bf69604856a6dc6819"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_amd64.tar.gz"
      sha256 "e5d6f2d59468f3d22cbba08b9e8b66351c8d2ad6551b713ef1980e8f7dfd9404"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_arm64.tar.gz"
      sha256 "2ed0b1ae0c000ba2e106e334a161896b6e3b0fbee95a7c3277dd730603d94345"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  test do
    system "#{bin}/anyrow --version"
  end
end
