# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyrow < Formula
  desc "CLI for the Anyrow extraction API"
  homepage "https://anyrow.ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_amd64.tar.gz"
      sha256 "7acd8aa3bc7f3177798d2c19f36a3b1c85a1ed5432c96b84c5b90f6cd8b7395f"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_arm64.tar.gz"
      sha256 "186886da9bcbd104b16df6baa5fc90e97bec6a03e206c161db7b1f3ea53a85eb"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_amd64.tar.gz"
      sha256 "733242064702b18b585f70d660f28e6104192aa344665c99f6e78cadb08b355c"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_arm64.tar.gz"
      sha256 "41a07222b6fec42f1e9e509a1d8c934242c0c80f06baa876ea98b1d35d969e5a"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  test do
    system "#{bin}/anyrow --version"
  end
end
