# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anyrow < Formula
  desc "CLI for the Anyrow extraction API"
  homepage "https://anyrow.ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_amd64.tar.gz"
      sha256 "152fcabdfc441260938905ea25c1bd2fc957395c1b9f24b82076bf35c42e8c5f"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_darwin_arm64.tar.gz"
      sha256 "ccb6682e2eac1037d7e6718db1eba380dd96ed86522d5afaf900c768ace8a3b5"

      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_amd64.tar.gz"
      sha256 "61df86c42d5836759444d4b79a8af5b96b3ba2e36580532edfb681fc8912fc6e"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyrow/cli/releases/download/v1.0.0/anyrow_1.0.0_linux_arm64.tar.gz"
      sha256 "76fe32389970a206346760c3a7d3eba1f5da0e7b7152e87502d35df2360c4882"
      define_method(:install) do
        bin.install "anyrow"
      end
    end
  end

  test do
    system "#{bin}/anyrow --version"
  end
end
